### ISSUE TITLE
Refactoring - Break complex methods

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/living-doc-generator#12]
- break down complex long methods into several smaller ones, that are atomic
- refactor consolidate_features_with_project() as it is suggested in: https://github.com/AbsaOSS/living-doc-generator/pull/2/files#r1603412467
- make some methods more general and add them to utils folder
- main method pattern refactoring with best practice (via https://realpython.com/python-main-function/)
```
def main():
    data = "My data read from the Web"
    print(data)

if __name__ == "__main__":
    main()
```

**Comment by MobiTikula** [comment]
This issue was originally made during the first phase of migrating the POC from script based into OOP solution: https://github.com/AbsaOSS/living-doc-generator/issues/3. For the current POC state, this issue is outdated. All the points were solved during the development, mainly by implementing OOP and suggestions from the Pylint tool.

Outdated points:

- [ ] break down complex long methods into several smaller ones, that are atomic
- done with migrating into OOP

- [ ] refactor consolidate_features_with_project() as it is suggested in: https://github.com/AbsaOSS/living-doc-generator/pull/2/files#r1603412467
- not having this method anymore, since we put all the logic into one `generator.py` file

- [ ] make some methods more general and add them to utils folder
- we made a utils folder, where we have multiple helping scripts such as: constants, decorators, utils etc.

- [ ] main method pattern refactoring with best practice (via https://realpython.com/python-main-function/)
- it is done by putting all the logic into one `generator.py` file
